CREATE TABLE lakeWaterTemps(
    Id VARCHAR(36) NOT NULL,
    TempInFahrenheit DECIMAL(6,2) NOT NULL, 
    TempInCelsius DECIMAL(6,2) NOT NULL, 
    WaterTempTimeStamp DATETIME NOT NULL,
    LakeId VARCHAR(36) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    UpdatedAt TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (Id),
    FOREIGN KEY (LakeId) REFERENCES lakes(Id));