CREATE TABLE lakeWaterLevels(
    Id VARCHAR(36) NOT NULL,
    SurfaceElevation DECIMAL(6,2) NOT NULL, 
    WaterLevelTimeStamp DATETIME NOT NULL,
    LakeId VARCHAR(36) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    UpdatedAt TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (Id),
    FOREIGN KEY (LakeId) REFERENCES lakes(Id));